# Generated by Django 5.2.1 on 2025-05-27 18:54

import django.db.models.deletion
import reclamos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG', upload_to=reclamos_app.models.archivo_reclamo_path, verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='reclamos_app.reclamo')),
            ],
            options={
                'verbose_name': 'Archivo de Reclamo',
                'verbose_name_plural': 'Archivos de Reclamos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
